# Generated by Django 5.2.4 on 2025-07-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus', '0003_alter_surplusitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
